<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style></style>
  </head>
  <body>
    <script>
      const p = new Promise((res, rej) => {
        setTimeout(() => {
          res("用户数据");
          rej("失败啦");
        }, 1000);
      });
      //调用then方法返回的还是Promise对象，这个对象的状态由回调函数的执行结果决定
      const a = p.then(
        (res) => {
          //1. 如果回调函数返回的时 非promise类型的属性，状态为成功，返回值为对象的成功的值。
          // console.log(res);
          // return res;
          // 2.如果返回的是Promise对象的话，看返回的内部promiss对象是否成功，返回值为内部Promise返回的值.
          // return new Promise((res, rej) => {
          //   rej("err");
          // });
          //3.抛出错误,a的状态为失败，并且a的返回值为所throw抛出的内容
          throw "内部函数抛出的错误";
        },
        (err) => console.warn(err)
      );
      a.then((res) => {
        console.log(res);
      }).catch((err) => {
        console.log(err);
      });
      console.log(a); //这里会先返回undefined，然后值会被修改为成功值
    </script>
  </body>
</html>
